apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
  namespace: rentalsystem
spec:
  service: rentalsapi
  backends:
  - service: rentalsapi
    weight: 500m
  - service: error-injector
    weight: 500m